function [ aon ] = Aon0SurfHFinOrd2( omega0 , k0 , epsilon , ~ , ~ , ~ , H , Sigma , ~ )
% Aon0SurfHFinOrd2 returns the dimensional onset acceleration for the second-order no-surfactant finite-depth case.

VH = + 2 * Sigma * cosh(2*H) ...
     + sinh(2*H) ...
     + 2 * H ...
     - 2 * Sigma;

aon = ( omega0^2 / k0 ) * ( ...
    epsilon * ( ...
        sqrt(2) * csch(H)^2 ...
    ) ...
    + epsilon^2 * ( ...
        ( ...
            4 * coth(H) * ( ...
                + 4 * Sigma * cosh(2*H) ...
                + cosh(3*H) * csch(H) ...
                + 4 * H ...
                - 2 * Sigma ...
            ) ...
        )/( ...
            VH ...
        ) ...
	) ...
    );


end


