function [ aon ] = Aon0SurfHInfOrd2( omega0 , k0 , epsilon , ~ , ~ , ~ , ~ , ~ , ~ )
% Aon0SurfHInfOrd2 returns the dimensional onset acceleration for the second-order no-surfactant infinite-depth case.

aon = ( omega0^2 / k0 ) * ( ...
    epsilon * ( ...
        0 ...
    ) ...
    + epsilon^2 * ( ...
        8 ...
	) ...
    );


end


