function [ aon ] = Aon0SurfHInfOrd3( omega0 , k0 , epsilon , ~ , ~ , ~ , ~ , ~ , ~ )
%Aon0SurfHInfOrd3 returns the dimensional onset acceleration for the third-order no-surfactant infinite-depth case.

aon = ( omega0^2 / k0 ) * ( ...
    epsilon * ( ...
        0 ...
    ) ...
    + epsilon^2 * ( ...
        8 ...
	) ...
    + epsilon^3 * ( ...
        -4 * sqrt(2) ...
    ) ...
    );


end


