function [ aon ] = Aon0SurfHInfOrd5( omega0 , k0 , epsilon , ~ , ~ , ~ , ~ , ~ , G )
%Aon0SurfHInfOrd5 returns the dimensional onset acceleration for the fifth-order no-surfactant infinite-depth case.

aon = ( omega0^2 / k0 ) * ( ...
    epsilon * ( ...
        0 ...
    ) ...
    + epsilon^2 * ( ...
        8 ...
	) ...
    + epsilon^3 * ( ...
        -4 * sqrt(2) ...
    ) ...
    + epsilon^4 * ( ...
        0 ...
    ) ...
    + epsilon^5 * ( ...
        ( 2 * sqrt(2) * ( -11 + 2 * G ) )/( -3 + 2 * G ) ...
    ) ...
    );


end


