function [ aon ] = AonGSurfHFinOrd1( omega0 , k0 , epsilon , M , B , Di , H , ~ , ~ )
% AonGSurfHFinOrd1 returns the dimensional onset acceleration for the first-order surfactant-covered finite-depth case.  This is the general case.
%
% In this context Di = 1/Pe and does not equal the diffusivity.

VS = 1 ...
    + sqrt(2) * B ...
    + B^2 ...
    + M*( ...
        sqrt(2) ...
        + 2 * B ...
        + M / Di ...
        - sqrt(2) / Di ...
    )/( ...
        1/Di ...
        + Di ...
    );

aon = ( omega0^2 / k0 ) * ( ...
    epsilon * ( ...
        sqrt(2) * ( ...
            VS * csch(H)^2 ...
            + coth(H)^2 * ( ...
                VS ...
                - 1 ...
                + sqrt(2) * M / ( 1 + Di^2 ) ...
            ) ...
        )/( ...
            VS ...
        ) ...
    ) ...
    );


end


